services:
  redis-spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      redisnet:
        ipv4_address: 192.168.10.61
  redis1:
    container_name: redis1
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      redisnet:
        ipv4_address: 192.168.10.2

  redis2:
    container_name: redis2
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      redisnet:
        ipv4_address: 192.168.10.3

  redis3:
    container_name: redis3
    image: redis
    ports:
      - "6381:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      redisnet:
        ipv4_address: 192.168.10.4

  redis4:
    container_name: redis4
    image: redis
    ports:
      - "6382:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      redisnet:
        ipv4_address: 192.168.10.5

  redis5:
    container_name: redis5
    image: redis
    ports:
      - "6383:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      redisnet:
        ipv4_address: 192.168.10.6

  redis6:
    container_name: redis6
    image: redis
    ports:
      - "6384:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      redisnet:
        ipv4_address: 192.168.10.7

networks:
  redisnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1